name: dummy
permissions:
  contents: read
  checks: write
on:
  push:
    branches: [main]
  pull_request:
jobs:
  verify:
    name: dummy
    uses: ./.github/workflows/rust.yml
    secrets: inherit
  pages:
    name: pages-dummy
    uses: ./.github/workflows/pages.yml
    secrets: inherit
